name: CI

# ワークフロー実行タイミング
on:
  # TODO: うまい具合に修正する
  # mainブランチへのプッシュとプルリクエストで実行
  push:
    branches: [ "github-actions" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # UT jobの定義
  UT:
    # TODO：自作のイメージから実行できるように
    # CI実行用のイメージ
    runs-on: ubuntu-latest

    # TODO：目的の処理をできるように修正
    # 実際の処理
    steps:
      # リポジトリのチェックアウト（現在参照しているブランチの資材を取得）
      - name: Checkout repository
        uses: actions/checkout@v3
      # Goのインストール
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.10'
          cache: true
      # ブランチの向き先確認
      - name: Check branch
        run: git branch
      # Goバージョンの確認
      - name: Check Go version
        run: go version
      # # 静的解析
      # - name: Go Lint
      #   uses: golangci/golangci-lint-action@v3
      # # ビルド
      # - name: Go Build
      #   run: |
      #     cd practice
      #     go build -v -o app .
      # UTの実行
      - name: Run tests
        run: go test -v ./... -coverprofile=coverage.out -covermode=atomic