name: CI

# ワークフロー実行タイミング
on:
  # TODO: うまい具合に修正する
  # mainブランチへのプッシュとプルリクエストで実行
  push:
    branches: [ "github-actions" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ジョブの定義
jobs:
  ut:
    # TODO：自作のイメージから実行できるように
    # CI実行用のイメージ
    runs-on: ubuntu-latest
    # 実際の処理
    steps:
      # リポジトリのチェックアウト（現在参照しているブランチの資材を取得）
      - name: Checkout repository
        uses: actions/checkout@v3
      # Goのインストール
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.10'
          cache: true
      # ブランチの向き先確認
      - name: Check branch
        run: git branch
      # Goバージョンの確認
      - name: Check Go version
        run: go version
      # UTの実行
      - name: Run tests
        run: go test -v ./... -coverprofile=coverage.out -covermode=atomic
        working-directory: src
  lint:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト（現在参照しているブランチの資材を取得）
      - name: Checkout repository
        uses: actions/checkout@v3
      # Goのインストール
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.10'
          cache: true
      # 静的解析
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: src
  docker-build:
    runs-on: ubuntu-latest
    needs: [ut, lint]
    steps:
      # リポジトリのチェックアウト（現在参照しているブランチの資材を取得）
      - name: Checkout repository
        uses: actions/checkout@v3
      # Goのインストール
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.10'
          cache: true
      # Docker Buildxのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # 移動
      - name: Change directory to src
        run: cd src
      # ビルド
      - name: Go Build
        run: go build -v -o app .
      # Dockerイメージのビルド
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg GOOS=linux \
            --build-arg GOARCH=amd64 \
            --build-arg GOARM=7 \
            -t practice-cloud-run-functions:latest .
            