name: CI

# ワークフロー実行タイミング
on:
  # mainブランチへのプッシュとプルリクエストで実行
  push:
    branches: [ "github-actions" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # TODO: 自作のイメージから実行できるように
    # CI実行用のイメージ
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # チェックアウト先のリポジトリを取得
      - uses: actions/checkout@master

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.